[tool.poetry]
name = "finance-tests"
version = "0.1.0"
description = ""
authors = ["Lucas Soranzo"]

[tool.poetry.dependencies]
python = "^3.8"
yfinance = "^0.1.74"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
